server:
  port: 8080

spring:
  liquibase:
    enabled: true
    changeLog: "classpath:db/changelog/db.changelog-master.yaml"
    drop-first: ${STOCK_MANAGEMENT_LIQUIBASE_ENABLE_DROP_FIRST:false}

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  datasource:
    url: jdbc:mysql://${STOCK_MANAGEMENT_DB_IP:localhost}:${STOCK_MANAGEMENT_DB_PORT:3306}/stock_management
    username: ${STOCK_MANAGEMENT_DB_USERNAME:root}
    password: ${STOCK_MANAGEMENT_DB_PASSWORD:root1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

stock-management:
  db:
    name: mysql
    maximum-pool-size: 5
    connection-timeout: 180000
    maximum-lifetime: 170000